update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -84,7 +84,15 @@ log 'Install tmux plugins'
 if [ ! -d "$HOME"/.tmux/plugins/tpm ]; then
     git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
 fi
-"$HOME"/.tmux/plugins/tpm/bin/install_plugins
+# install_plugins は tmux サーバの環境変数 TMUX_PLUGIN_MANAGER_PATH を読む。tpm を clone する前から
+# 起動していたサーバはこれを持たないため、設定を読み直させて tpm 本体を走らせる。
+if tmux list-sessions >/dev/null 2>&1; then
+    tmux source-file "$HOME"/.tmux.conf
+fi
+# tmux 側の都合で失敗しても以降の LSP/lint セットアップまで巻き込まない
+if ! "$HOME"/.tmux/plugins/tpm/bin/install_plugins; then
+    log 'tmux plugin installation failed, run "prefix + I" inside tmux to retry'
+fi
 
 ###########################################################
 # Install Neovim plugins (lazy.nvim)
